# Generated by Django 4.2.11 on 2025-03-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_seat_movie_alter_seat_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
    ]
